#define NUM_HEAD 36
#define NUM_CHEST 37
#define NUM_GLOVES 39
#define NUM_LEGS 34

float head[NUM_HEAD] = {4.2f, 3.0f, 6.0f, 5.0f, 0.7f, 2.5f, 2.2f, 5.1f, 1.2f, 4.5f, 4.8f, 0.4f, 3.8f, 0.8f, 4.7f, 8.0f, 3.5f, 6.3f, 1.4f, 6.5f, 7.2f, 7.5f, 4.1f, 3.0f, 1.1f, 2.6f, 0.9f, 1.5f, 5.5f, 0.6f, 3.9f, 6.8f, 2.0f, 5.4f, 10.0f, 1.2f};
char *head_names[NUM_HEAD] = {"Balder Helm/Crystalline Helm/Helm of Artorias/Knight Helm", "Big Hat/Chain Helm/Crown of the Dark Sun/Crown of the Great Lord", "Black Iron Helm", "Black Knight Helm/Paladin Helm/Xanthous Crown", "Black Sorcerer Hat", "Bloated Head/Mask of Velka/Porcelain Mask", "Bloated Sorcerer Head", "Brass Helm/Elite Cleric Helm/Helm of The Wise", "Brigand Hood/Mask of the Child/Mask of the Mother/Pharis`s Hat/Priest`s Hat/Thief Mask", "Catarina Helm/Elite Knight Helm/Helm of Favor/Iron Helm/Royal Helm", "Cleric Helm/Silver Knight Helm", "Crown of Dusk", "Dark Mask", "Dingy Hood/Maiden Hood", "Eastern Helm", "Fang Boar Helm", "Gargoyle Helm/Standard Helm", "Giant Helm", "Gold-Hemmed Black Hood/Sunlight Maggot/Wanderer Hood", "Golem Helm/Gough`s Helm", "Guardian Helm", "Havel`s Helm", "Helm of Thorns", "Hollow Soldier Helm", "Hollow Thief`s Hood/Tattered Cloth Hood/Witch Hat", "Hollow Warrior Helm", "Mage Smith Hat/Shadow Mask/Sorcerer Hat", "Mask of the Sealer", "Ornstein`s Helm", "Painting Guardian Hood/Sack", "Six-Eyed Helm of the Channelers", "Smough`s Helm/Stone Helm", "Snickering Top Hat", "Steel Helm", "Symbol of Avarice", "Mask of the Father"};

float chest[NUM_CHEST] = {1.0f, 10.5f, 13.3f, 9.0f, 10.9f, 3.9f, 15.6f, 13.0f, 3.1f, 1.8f, 11.7f, 6.0f, 4.5f, 12.5f, 9.8f, 3.0f, 12.3f, 16.4f, 3.5f, 17.0f, 5.9f, 19.5f, 7.8f, 2.8f, 6.6f, 4.0f, 4.7f, 6.4f, 2.0f, 2.3f, 12.0f, 1.6f, 12.9f, 10.1f, 17.6f, 14.0f, 2.7f};
char *chest_names[NUM_CHEST] = {"Antiquated Dress", "Armor of Artorias/Armor of Thorns", "Armor of the Glorious/Elite Cleric Armor", "Armor of the Sun", "Balder Armor/Brass Armor/Crystalline Armor/Knight Armor", "Black Cleric Robe/Crimson Robe/Xanthous Overcoat", "Black Iron Armor", "Black Knight Armor/Gough`s Armor", "Black Leather Armor/Brigand Armor/Moonlight Robe", "Black Sorcerer Cloak", "Catarina Armor/Elite Knight Armor/Embraced Armor of Favor", "Chain Armor/Robe of the Great Lord", "Chester`s Long Coat", "Cleric Armor", "Dark Armor", "Dingy Robe", "Eastern Armor", "Giant Armor/Golem Armor", "Gold-Hemmed Black Cloak/Wanderer Coat", "Guardian Armor", "Hard Leather Armor", "Havel`s Armor", "Hollow Soldier Armor", "Hollow Thief`s Leather Armor", "Hollow Warrior Armor", "Holy Robe/Sage Robe/Witch Cloak", "Leather Armor", "Lord`s Blade Robe", "Maiden Robe", "Mage Smith Coat/Shadow Garb/Sorcerer Cloak", "Ornstein`s Armor/Silver Knight Armor", "Painting Guardian Robe", "Paladin Armor", "Robe of the Channelers", "Smough`s Armor/Stone Armor", "Steel Armor", "Tattered Cloth Robe"};

float gloves[NUM_GLOVES] = {0.6f, 3.5f, 9.2f, 6.0f, 1.8f, 1.0f, 2.8f, 5.4f, 6.9f, 1.5f, 7.4f, 0.8f, 6.4f, 5.8f, 1.2f, 7.8f, 3.7f, 4.6f, 5.0f, 3.0f, 6.2f, 9.7f, 7.0f, 10.4f, 11.5f, 4.3f, 3.6f, 1.4f, 0.5f, 4.0f, 0.9f, 7.6f, 5.5f, 8.3f, 1.6f, 0.7f, 2.1f, 1.7f, 2.3f};
char *gloves_names[NUM_GLOVES] = {"Antiquated Gloves", "Balder Gauntlets/Hard Leather Gauntlets/Knight Gauntlets", "Black Iron Gauntlets", "Black Knight Gauntlets", "Black Leather Gloves/Black Manchette/Brigand Gauntlets", "Black Sorcerer Gauntlets", "Bracelet of the Great Lord/Leather Gloves/Lord`s Blade Gloves", "Brass Gauntlets", "Catarina Gauntlets", "Chester`s Gloves/Eastern Gauntlets", "Cleric Gauntlets", "Crimson Gloves", "Crystalline Gauntlets", "Dark Gauntlets", "Dingy Gloves/Gold-Hemmed Black Gloves/Maiden Gloves", "Elite Cleric Gauntlets", "Elite Knight Gauntlets", "Gauntlets of Artorias", "Gauntlets of Favor", "Gauntlets of the Channelers/Gauntlets of the Vanquisher", "Gauntlets of Thorns", "Giant Gauntlets/Golem Gauntlets", "Gough`s Gauntlets", "Guardian Gauntlets/Smough`s Gauntlets/Stone Gauntlets", "Havel`s Gauntlets", "Iron Bracelet", "Leather Gauntlets", "Mage Smith Gauntlets/Shadow Gauntlets/Sorcerer Gauntlets", "Moonlight Gloves", "Ornstein`s Gauntlets", "Painting Guardian Gloves", "Paladin Gauntlets", "Silver Knight Gauntlets", "Steel Gauntlets", "Tattered Cloth Manchette/Traveling Gloves", "Traveling Gloves", "Wanderer Manchette", "Witch Gloves", "Xanthous Gloves"};

float legs[NUM_LEGS] = {2.8f, 3.0f, 6.4f, 9.2f, 7.0f, 1.0f, 2.5f, 4.0f, 1.8f, 6.9f, 4.6f, 3.2f, 7.4f, 3.5f, 5.8f, 7.8f, 9.7f, 8.0f, 10.4f, 11.5f, 1.6f, 1.5f, 1.7f, 1.4f, 2.0f, 5.3f, 5.5f, 6.2f, 5.0f, 7.6f, 6.5f, 8.3f, 6.0f, 2.1f};
char *legs_names[NUM_LEGS] = {"Anklet of the Great Lord/Black Tights/Leather Boots", "Antiquated Skirt/Black Leather Boots/Gold-Hemmed Black Skirt", "Balder Leggings/Brass Leggings/Crystalline Leggings/Knight Leggings", "Black Iron Leggings", "Black Knight Leggings/Ornstein`s Leggings", "Black Sorcerer Boots", "Blood-Stained Skirt/Maiden Skirt/Witch Skirt", "Boots of the Explorer/Eastern Leggings/Painting Guardian Waistcloth/Xanthous Waistcloth", "Brigand Trousers/Moonlight Waistcloth", "Catarina Leggings/Elite Knight Leggings/Leggings of Favor", "Chain Leggings", "Chester`s Trousers", "Cleric Leggings", "Crimson Waistcloth/Hard Leather Boots", "Dark Leggings", "Elite Cleric Leggings", "Giant Leggings/Golem Leggings", "Gough`s Leggings", "Guardian Leggings/Smough`s Leggings/Stone Leggings", "Havel`s Leggings", "Heavy Boots/Traveling Boots", "Hollow Soldier Waistcloth", "Hollow Thief`s Tights", "Hollow Warrior Waistcloth/Mage Smith Boots/Shadow Leggings/Sorcerer Boots", "Holy Trousers", "Iron Leggings", "Leggings of Artorias", "Leggings of Thorns", "Lord`s Blade Waistcloth", "Paladin Leggings", "Silver Knight Leggings", "Steel Leggings", "Waistcloth of the Channelers", "Wanderer Boots"};
